version: "3.8"

services:
  web:
    build: .
    container_name: fastapi-app-template
    ports:
      - "8000:8000"
    depends_on:
      - cockroachdb-1
      - cockroachdb-2
      - cockroachdb-3
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    volumes:
      - ./app:/app/app
    # command: >
    #   sh -c "fastapi dev app/main.py --proxy-headers --host 0.0.0.0 --port 8000"
    command: >
      sh -c "python server.py --dev"
    env_file:
      - ./.env

  cockroachdb-1:
    image: cockroachdb/cockroach:v24.1.0
    container_name: cockroachdb-1
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data-1:/cockroach/cockroach-data

  cockroachdb-2:
    image: cockroachdb/cockroach:v24.1.0
    container_name: cockroachdb-2
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    volumes:
      - cockroach-data-2:/cockroach/cockroach-data

  cockroachdb-3:
    image: cockroachdb/cockroach:v24.1.0
    container_name: cockroachdb-3
    command: start --insecure --join=cockroachdb-1,cockroachdb-2,cockroachdb-3
    volumes:
      - cockroach-data-3:/cockroach/cockroach-data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   env_file:
  #     - ./.env

volumes:
  cockroach-data-1:
  cockroach-data-2:
  cockroach-data-3:
  # pgadmin-data:
